name: 02-Fallback CI

on:
  push:
    branches: [main]
    paths:
    - 'contracts/challenges/02-Fallback.sol'
    - 'contracts/attackers/FallbackAttacker.sol'
    - 'test/02-Fallback.test.ts'

  pull_request:
    branches: [main]
    paths:
    - 'contracts/challenges/02-Fallback.sol'
    - 'test/02-Fallback.test.ts'

env:
  
jobs:
  start-hardhat-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: yarn install
      
      - name: Test verification
        run: yarn test test/02-Fallback.test.ts
